### ISSUE TITLE
bigwigmerge: thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by ghuls** [jackh726/bigtools#11]
```bash
$ RUST_BACKTRACE=1 bigwigmerge -b mouse.bw -b human.bw -b macaque.bw -b marmoset.bw all_species.bw
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/bin/bigwigmerge.rs:139:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: bigwigmerge::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

UCSC bigWigMerge works fine on those files:
```bash
$ bigWigMerge mouse.bw human.bw macaque.bw marmoset.bw all_species.bedGraph
Got 87 chromosomes from 4 bigWigs
Processing.......................................................................................
```

Each bigwig has all chromosomes:
```
$ bigWigInfo -chroms mouse.bw
version: 4
isCompressed: yes
isSwapped: 0
primaryDataSize: 289,634,826
primaryIndexSize: 847,988
zoomLevels: 8
chromCount: 87
        mouse_chr1 0 195471971
        mouse_chr10 1 130694993
        mouse_chr11 2 122082543
        mouse_chr12 3 120129022
        mouse_chr13 4 120421639
        mouse_chr14 5 124902244
        mouse_chr15 6 104043685
        mouse_chr16 7 98207768
        mouse_chr17 8 94987271
        mouse_chr18 9 90702639
        mouse_chr19 10 61431566
        mouse_chr2 11 182113224
        mouse_chr3 12 160039680
        mouse_chr4 13 156508116
        mouse_chr5 14 151834684
        mouse_chr6 15 149736546
        mouse_chr7 16 145441459
        mouse_chr8 17 129401213
        mouse_chr9 18 124595110
        mouse_chrX 19 171031299
        human_chr1 20 248956422
        human_chr10 21 133797422
        human_chr11 22 135086622
        human_chr12 23 133275309
        human_chr13 24 114364328
        human_chr14 25 107043718
        human_chr15 26 101991189
        human_chr16 27 90338345
        human_chr17 28 83257441
        human_chr18 29 80373285
        human_chr19 30 58617616
        human_chr2 31 242193529
        human_chr20 32 64444167
        human_chr21 33 46709983
        human_chr22 34 50818468
        human_chr3 35 198295559
        human_chr4 36 190214555
        human_chr5 37 181538259
        human_chr6 38 170805979
        human_chr7 39 159345973
        human_chr8 40 145138636
        human_chr9 41 138394717
        human_chrX 42 156040895
        macaque_chr1 43 223616942
        macaque_chr2 44 196197964
        macaque_chr3 45 185288947
        macaque_chr4 46 169963040
        macaque_chr5 47 187317192
        macaque_chr6 48 179085566
        macaque_chr7 49 169868564
        macaque_chr8 50 145679320
        macaque_chr9 51 134124166
        macaque_chr10 52 99517758
        macaque_chr11 53 133066086
        macaque_chr12 54 130043856
        macaque_chr13 55 108737130
        macaque_chr14 56 128056306
        macaque_chr15 57 113283604
        macaque_chr16 58 79627064
        macaque_chr17 59 95433459
        macaque_chr18 60 74474043
        macaque_chr19 61 58315233
        macaque_chr20 62 77137495
        macaque_chrX 63 153388924
        marmoset_chr1 64 217961735
        marmoset_chr2 65 204486479
        marmoset_chr3 66 191910223
        marmoset_chr4 67 174041770
        marmoset_chr5 68 164351765
        marmoset_chr6 69 161003406
        marmoset_chr7 70 157546058
        marmoset_chr8 71 126850804
        marmoset_chr9 72 134044658
        marmoset_chr10 73 137671225
        marmoset_chr11 74 129688756
        marmoset_chr12 75 124486764
        marmoset_chr13 76 118934817
        marmoset_chr14 77 112090317
        marmoset_chr15 78 99198953
        marmoset_chr16 79 97817134
        marmoset_chr17 80 74942703
        marmoset_chr18 81 47031477
        marmoset_chr19 82 51570929
        marmoset_chr20 83 45615054
        marmoset_chr21 84 51259342
        marmoset_chr22 85 51300780
        marmoset_chrX 86 148168104
basesCovered: 1,932,598,589
mean: 0.116719
min: 0.014938
max: 271.738831
std: 0.333123
```

**Comment by ghuls** [comment]
Fixed by: https://github.com/jackh726/bigtools/commit/c43f2fa0b73d243031ff1af059d33a68c2deec29
